DROP TABLE IF EXISTS producte;

CREATE TABLE producte (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL,
    descripcion VARCHAR(100),
    stock BIGINT NOT NULL,
    price DECIMAL(5, 2) NOT NULL,
    rating DECIMAL(2, 1),
    `condition` ENUM('NOU', 'ANTIC', 'POC_USAT', 'MOLT_USAT'),
    status BOOLEAN NOT NULL,
    data_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);